INSERT INTO PRODUCTS (ID, CODE, NAME, DESCRIPTION, PRICE, INSTOCK)
VALUES (1, 'cup123', 'Cups', 'cUPS dESCRIPTION', 120, TRUE);

INSERT INTO PRODUCTS (ID, CODE, NAME, DESCRIPTION, PRICE, INSTOCK)
VALUES (2, 'pencil123', 'Pencil', 'pENCIL dESCRIPTION', 111, TRUE);

INSERT INTO PRODUCTS (ID, CODE, NAME, DESCRIPTION, PRICE, INSTOCK)
VALUES (3, 'pen123', 'Pen', 'pENS dESCRIPTION', 222, FALSE);

INSERT INTO PRODUCTS (ID, CODE, NAME, DESCRIPTION, PRICE, INSTOCK)
VALUES (4, 'mouse123', 'mouse', 'mouse dESCRIPTION 2', 1311, TRUE);